---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev1-spring-music
  namespace: dev1-ns
spec:
  interval: 1m0s
  ref:
    branch: dev1-rollingdemo
  url: https://github.com/musk8teers/spring-music
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev1
  namespace: dev1-ns
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev1
  sourceRef:
    kind: GitRepository
    name: dev1-spring-music